show-model-warnings: false
auto-commits: true
watch-files: true
analytics-disable: true
show-release-notes: false
gitignore: false

# experimental 
gui: false
copy-paste: false

# large language models
# https://aider.chat/docs/llms.html

model: gemini-exp
editor-model: gemini
weak-model: gemini/gemini-2.0-flash

# model names
#
# gemini
# gemini-exp
# gemini/gemini-2.0-flash
# openrouter/anthropic/claude-3.7-sonnet
# openrouter/anthropic/claude-3.5-sonnet
# openrouter/openai/gpt-4o-mini
# openrouter/openai/o3-mini
# openrouter/openai/o1
# openrouter/openai/gpt-4
# openrouter/deepseek/deepseek-coder
# openrouter/deepseek/deepseek-chat-v3-0324
# openrouter/deepseek/deepseek-r1
# deepseek/deepseek-chat
# deepseek/deepseek-coder
# deepseek/deepseek-reasoner
#
# API key environment variables
# https://aider.chat/docs/config/api-keys.html
# GEMINI_API_KEY
# OPENROUTER_API_KEY
# DEEPSEEK_API_KEY
# OPENAI_API_KEY
# ANTHROPIC_API_KEY
