GOOSE_MODE: smart_approve
extensions:
  computercontroller:
    bundled: true
    display_name: Computer Controller
    enabled: false
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    bundled: true
    display_name: Developer Tools
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  git:
    args:
    - mcp-server-git
    bundled: null
    cmd: uvx
    description: Git version control system integration
    enabled: false
    env_keys: []
    envs: {}
    name: git
    timeout: 300
    type: stdio
  vscode:
    args:
    - vscode-mcp-server
    bundled: null
    cmd: npx
    description: Provides a VSCode IDE integration for development workflows
    enabled: false
    env_keys: []
    envs: {}
    name: vscode
    timeout: 300
    type: stdio
GOOSE_MODEL: gemini-2.5-flash-preview-04-17
GOOSE_PROVIDER: google